# Generated by Django 5.2.16 on 2026-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional — shown to you in the dashboard only; the site shows numbered cards.",
                        max_length=80,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers show first (this sets the № on the card).",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        default="08149946164",
                        help_text="Main phone number shown on the site.",
                        max_length=20,
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        default="09150512286",
                        help_text="Second phone number (optional).",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="2348149946164",
                        help_text="WhatsApp number in international format, digits only (e.g. 2348149946164). Used for all booking buttons.",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_link",
                    models.URLField(
                        blank=True,
                        default="https://wa.me/message/IJYB6PG5A4FGM1",
                        help_text="Official WhatsApp business short link (wa.me/message/...). Leave empty to use the WhatsApp number instead.",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        default="No. 38 Okigwe Road, beside DSTV Office", max_length=120
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        default="by IMSU Junction, Orji — Owerri, Imo State",
                        max_length=120,
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        default="https://www.instagram.com/naoberry_signature"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        default="https://web.facebook.com/profile.php?id=61557655057446"
                    ),
                ),
                (
                    "stat_looks",
                    models.PositiveIntegerField(
                        default=200,
                        help_text='"Signature looks" number shown on the homepage.',
                    ),
                ),
                (
                    "stat_brides",
                    models.PositiveIntegerField(
                        default=100, help_text='"Brides & celebrants" number.'
                    ),
                ),
                (
                    "stat_students",
                    models.PositiveIntegerField(
                        default=50, help_text='"Students trained" number.'
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="The big photo at the top of the site (portrait works best).",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "artist_image",
                    models.ImageField(
                        blank=True,
                        help_text='Photo of Naomi in "The Artist" section.',
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "class_image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo in the makeup classes section.",
                        null=True,
                        upload_to="site/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="students/")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional — for your own reference in the dashboard.",
                        max_length=80,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Certified student",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="What the client said — keep it short and real."
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text='Who said it, e.g. "A Naoberry bride, Owerri".',
                        max_length=80,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="works/")),
                (
                    "caption",
                    models.CharField(
                        help_text='Short caption shown on the photo, e.g. "Crowned for the aisle".',
                        max_length=80,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bridal", "Bridal"),
                            ("owanbe", "Owanbe"),
                            ("glam", "Glam"),
                            ("transform", "Before / After"),
                            ("studio", "Studio"),
                        ],
                        default="glam",
                        max_length=12,
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("4/5", "Tall (4:5)"),
                            ("3/4", "Taller (3:4)"),
                            ("1/1", "Square (1:1)"),
                        ],
                        default="4/5",
                        help_text="Tile shape in the gallery grid — mixing shapes looks best.",
                        max_length=4,
                    ),
                ),
                (
                    "instagram_link",
                    models.URLField(
                        default="https://www.instagram.com/naoberry_signature",
                        help_text="Link to this exact Instagram post (or leave the profile link).",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers show first. The first 12 are on the front page.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Gallery look",
                "verbose_name_plural": "Gallery looks",
                "ordering": ["order", "id"],
            },
        ),
    ]
